/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package SI_lab2_173158;

import org.junit.Test;
import static org.junit.Assert.*;

public class PrimeExampleTest {
    @Test public void testPrimeExampleHasAGreeting() {
    	PrimeExample classUnderTest = new PrimeExample();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
