/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package SI_lab2_173158;

public class PrimeExample {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new PrimeExample().getGreeting());
    }
}
